### ISSUE TITLE
[Bug]: Plugin version not correct (1.20.4)

### ISSUE THREAD

**Issue by KapiteinDennis** [Wolfieheart/ArmorStandEditor#532] opened 2024-06-12 12:16 UTC
### Expected behavior

When you update the plugin to the latest version, that you don't get a notification in console and chat that there is a new version.

### Observed/Actual behavior

When updating the plugin you get this message in chat, and in the console.
I even deleted the config and had it recreated.
![version](https://github.com/Wolfieheart/ArmorStandEditor/assets/25269104/fc7d52d9-3c72-4033-9e5f-34a54339d531)

### Steps/models to reproduce

Install the plugin on PurpurMC 1.20.4 with the default config.

### Plugin list

PlaceholderAPI
ProtocolLib
WorldEdit
WorldGuard
ArmorStandTools
ArmorStandEditor-1.20.6-46.2

### Plugin Version

armorstandeditor-1.20.6-46.2

### Server Version

PurpurMC 1.20.4
![mcversion](https://github.com/Wolfieheart/ArmorStandEditor/assets/25269104/6f2f8dbb-6c75-4f39-804f-4f9c87fd4a8b)

**Comment by Wolfieheart** [comment] 2024-06-12 14:02
As much as I appreciate this being brought to my attention. This is a temporary issue caused by the UpdateChecker (which I dont maintain) and it reading the information it gets from Spigot directly.

Once ASE also moves to 1.21-47 this will be fixed completely as the version wont be a (HOTFIX) and will result in everything being back in line again.

**Comment by KapiteinDennis** [comment] 2024-06-12 16:17
Could you maybe add an option to the config, to disable the notifications?

**Comment by Wolfieheart** [comment] 2024-06-12 16:20
There should already be one as:
```
#----------- UPDATE NOTIFICATIONS
# Enable or Disable the Update Checker
runTheUpdateChecker: true

# Set this to allow your operators to get messages in game w.r.t Plugin updates
opUpdateNotification: false
```

**Comment by KapiteinDennis** [comment] 2024-06-12 18:12
I overlooked that, sorry!

**Comment by Wolfieheart** [comment] 2024-06-12 18:37
> I overlooked that, sorry!

No worries :D It happens :D

**Closed** 2024-07-26 20:53 UTC
Labels: bug, BUG-0: Pending Investigation
