### ISSUE TITLE
Add hex color support in plugin

### ISSUE THREAD

**Issue by Zeith22** [Wolfieheart/ArmorStandEditor#409] opened 2023-12-31 00:05 UTC
### Is your feature request related to a problem?

No

### Describe the solution you'd like.

-

### Describe alternatives you've considered.

-

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Wolfieheart** [comment] 2024-01-02 10:06
Duplicate of #125

**Closed by Wolfieheart** 2024-01-02 10:06 UTC
